### ISSUE TITLE
insert_by_period materializations

### ISSUE THREAD

**Issue by a-adamovich** [Teradata/dbt-teradata-utils#11]
### Describe the feature
The feature is already mentioned in [teradata_utils](https://hub.getdbt.com/Teradata/teradata_utils), but marked as "no plans to implement, please submit an issue if you need it"

### Describe alternatives you've considered
Not alternative at this moment, I tried to adopt the general solution, but didn't managed.

### Who will this benefit?
This feature is extremely necessary to overcome spool issue for our huge datasets. 

### Are you interested in contributing this feature?
I tried to solve it, but didn't managed.

**Comment by septimit** [comment]
Hi Aleksey,
insert_by_period materialization is now part of [dbt-labs-experimental-features](https://github.com/dbt-labs/dbt-labs-experimental-features) repo.
I have forked the repo and had a first go at tailoring insert_by_period materialization implementation for Teradata in [this branch](https://github.com/septimit/dbt-labs-experimental-features/tree/teradata_insert_by_period)

Here are some known limitations:
1. start_date and stop_date must to be specified as timestamps see this [sample model](https://github.com/septimit/dbt-labs-experimental-features/blob/teradata_insert_by_period/insert_by_period/integration_tests/models/test_insert_by_period.sql)
2. tmp tables (period0_tmp, period1_tmp ...) are not removed after the run is completed and can lead to failures on reruns
3. period granularity is limited to [INTERVAL arithmetic](https://docs.teradata.com/r/Enterprise_IntelliFlex_VMware/SQL-Date-and-Time-Functions-and-Expressions/Period-Functions-and-Operators/INTERVAL/INTERVAL-Syntax)
4. this list is not complete, since very little testing has been done on the code

I hope this code is useful and can unblock you,
Septi
